Zuzu-Typ/PyGLM

func_common.h
quaternion.h
type_mat2x2.h
type_mat2x3.h
type_mat2x4.h
type_mat3x2.h
type_mat3x3.h
type_mat3x4.h
type_mat4x2.h
type_mat4x3.h
type_mat4x4.h
type_vec2.h
type_vec3.h
type_vec4.h

Get an attribute name is different with python2, this fix a segfault with python 2.7, see issues #8

Get an attribute name is different with python2, this fix a segfault with python 2.7

---

matrix_transform.h

fix error message in scale()/scale_slow()

fix error message in scale()/scale_slow()

---

PyGLM.cpp

fixes https://github.com/Zuzu-Typ/PyGLM/issues/29

fix building with clang

---

.gitignore
.travis.yml
PyGLM_test.py

Travis Continuous Integration

---

PyGLM.cpp

\+ Added support for all stable extensions
\~ Using glm as gtc and detail namespaces now.
Waiting for fix of several glm issues
Should fix #28

Support for all stable extensions

---

PyGLM.cpp
glm/glm/detail/func_integer.inl
glm/glm/gtc/random.inl

Fixed warnings

---

PyGLM.cpp

Fixed vec3 constructor

---

PyGLM/imports.h
PyGLM/type_methods/qua.h

Changed quaternion component order to (w, x, y, z)

Fixed quaternion order

---

PyGLM/type_methods/mvec.h
PyGLM_test.py

Fixed mvec functions

---

PyGLM/functions/stable_extensions/random.h
PyGLM_test.py
generate_function_reference.py
wiki/function-reference/README.md
wiki/function-reference/README.sb
wiki/function-reference/recommended_extensions/README.md
wiki/function-reference/recommended_extensions/README.sb
wiki/function-reference/recommended_extensions/random.md
wiki/function-reference/recommended_extensions/random.sb

Added setSeed() function

---

.travis.yml
PyGLM/internal_functions/unpackers.h

Should support Python 3.9 now.

Python 3.9 support

---

PyGLM/internal_functions/helper_macros.h
PyGLM/type_methods/glmArray.h
PyGLM/type_methods/mat.h
PyGLM/type_methods/mvec.h
PyGLM/type_methods/qua.h
PyGLM/type_methods/vec.h
PyGLM/types/glmArray/forward_declarations.h
PyGLM/types/glmArray/glmArray.h
PyGLM_test.py
wiki/Using-arrays.md
wiki/Using-arrays.sb

+ Fixed incorrect string generation for subclasses of glm types.
+ Added the keyword argument `ctype` to `map()`

Small improvements

---

PyGLM/internal_functions/type_checkers.h

Was still requesting C-contiguous buffers (which don't have the correct order).

Fixed buffer type checking

---

PyGLM/type_methods/glmArray.h
PyGLM/type_methods/mat.h
PyGLM_test.py
wiki/Using-matrices.md
wiki/Using-matrices.sb

- Improved array_getbuffer compatibility with different flags.
- Fixed array initialization from non fortran-contiguous matrix buffers.
- Added option for custom diagonal matrix elements (#120)

Improved buffer protocol and diagonal elements

---

PyGLM/internal_functions/type_getters/mat.h
PyGLM/internal_functions/type_getters/vec.h
PyGLM/type_methods/glmArray.h
PyGLM/types/glmArray/forward_declarations.h
PyGLM/types/glmArray/glmArray.h
PyGLM_test.py
wiki/Using-arrays.md
wiki/Using-arrays.sb

Added `split_components()` and `reduce(function[, initializer])` methods to the array type (#123)

Added `array.split_components()` and `array.reduce()`

---

PyGLM/type_methods/glmArray.h
PyGLM/types/types.h

+ Replaced ssize_t with Py_ssize_t

Fix for Py 3.10

---

PyGLM/type_methods/mat.h
test/PyGLM_test.py

Added support for matrix initialization from quaternions (mat3, mat4)

---

PyGLM/functions/detail/func_common.h
PyGLM/internal_functions/packers.h
test/PyGLM_test.py
wiki/function-reference/detail/func_common.md
wiki/function-reference/detail/func_common.sb

Added support for iterable arguments for min and max

---

PyGLM/type_methods/mat.h

+ Added support for multiplication of matrices with vectors with homogenous coordinates

Added support for homogenous multiplication (#140)

---

PyGLM/internal_functions/type_checkers.h

+ Added support for initialization of matrices with C contiguous arrays (#138)
+ Fixed a bug where NxM buffers would be interpreted as MxN matrices.

Allowing for C contiguity

---

PyGLM/internal_functions/number_functions.h
PyGLM/internal_functions/type_checkers.h

Fixed two memory leaks ( #159 )

Fixed memory leaks

---

PyGLM/internal_functions/type_checkers.h

Fixed buffer protocol

---

PyGLM/internal_functions/type_checkers.h

Fixed tuple segfault

---

PyGLM/functions/stable_extensions/matrix_transform.h

Fix segfault

---

PyGLM.cpp
PyGLM/functions/other/all.h
PyGLM/functions/other/custom.h
test/PyGLM_test.py

Added vec4 <-> quat conversion methods

---

PyGLM/internal_functions/type_checkers.h
test/PyGLM_test.py

Fixed buffer object format not being identified correctly on some platforms

---

setup.py
version.h

+ Bumped version
+ Updated supported Python versions in setup.py

Bump version (2.7.0)

---

PyGLM/internal_functions/type_checkers.h

+ Added support for non-contiguous buffers
+ Streamlined non-F-contiguous buffer retrieval
+ Should fix #205

Improve buffer protocol

---

PyGLM/type_methods/glmArray.h
test/PyGLM_test.py

I took at stab at fixing #210.  Not sure if I did it right, the variable names were confusing.  But I think I'm on to something.

Fix #210: matrix multiplication of array of vectors

---

PyGLM/functions/stable_extensions/matrix_transform.h
PyGLM/internal_functions/error_functions.h

minor changes fixing the segfault described in the issue #231

fix segfault #231

---

.github/workflows/test.yml

Test runs now only compile PyGLM once.

Fix double test runs in GitHub Actions

---

.github/workflows/deploy-test-pypi.yml
.github/workflows/deploy.yml

Updated `actions/upload-artifact` and `actions/download-artifact` to v4
Updated `gh-action-pypi-publish` to v1.10.3

Updated actions dependencies

---

setup.cfg

It's nice to have these quick links on PyPI and I guess there are some tools using them as well.

Add projects urls to setup.cfg

---

glm/__init__.py

Increase stack level in `import glm` warning
